/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ServicesIndexRouteImport } from './pages/services/index'
import { Route as DevIndexRouteImport } from './pages/dev/index'
import { Route as DevPrototypeFolderExampleIndexRouteImport } from './pages/dev/prototype-folder-example/index'
import { Route as DevFuzzySearchIndexRouteImport } from './pages/dev/fuzzy-search/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPrototypeFolderExampleIndexRoute =
  DevPrototypeFolderExampleIndexRouteImport.update({
    id: '/dev/prototype-folder-example/',
    path: '/dev/prototype-folder-example/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevFuzzySearchIndexRoute = DevFuzzySearchIndexRouteImport.update({
  id: '/dev/fuzzy-search/',
  path: '/dev/fuzzy-search/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/': typeof DevIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/dev/fuzzy-search/': typeof DevFuzzySearchIndexRoute
  '/dev/prototype-folder-example/': typeof DevPrototypeFolderExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevIndexRoute
  '/services': typeof ServicesIndexRoute
  '/dev/fuzzy-search': typeof DevFuzzySearchIndexRoute
  '/dev/prototype-folder-example': typeof DevPrototypeFolderExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/': typeof DevIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/dev/fuzzy-search/': typeof DevFuzzySearchIndexRoute
  '/dev/prototype-folder-example/': typeof DevPrototypeFolderExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/'
    | '/services/'
    | '/dev/fuzzy-search/'
    | '/dev/prototype-folder-example/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/services'
    | '/dev/fuzzy-search'
    | '/dev/prototype-folder-example'
  id:
    | '__root__'
    | '/'
    | '/dev/'
    | '/services/'
    | '/dev/fuzzy-search/'
    | '/dev/prototype-folder-example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevIndexRoute: typeof DevIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  DevFuzzySearchIndexRoute: typeof DevFuzzySearchIndexRoute
  DevPrototypeFolderExampleIndexRoute: typeof DevPrototypeFolderExampleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/prototype-folder-example/': {
      id: '/dev/prototype-folder-example/'
      path: '/dev/prototype-folder-example'
      fullPath: '/dev/prototype-folder-example/'
      preLoaderRoute: typeof DevPrototypeFolderExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/fuzzy-search/': {
      id: '/dev/fuzzy-search/'
      path: '/dev/fuzzy-search'
      fullPath: '/dev/fuzzy-search/'
      preLoaderRoute: typeof DevFuzzySearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevIndexRoute: DevIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  DevFuzzySearchIndexRoute: DevFuzzySearchIndexRoute,
  DevPrototypeFolderExampleIndexRoute: DevPrototypeFolderExampleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
